name: Image optimizer prod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy-azure-image-optimizer.yml'
      - 'apps/image-optimizer-azure/**'
      - 'packages/image-handling/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'untitled-image-api' # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'apps/image-optimizer-azure/azure' # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '20.5.1'

concurrency:
  group: 'image-optimizer'
  cancel-in-progress: true
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-install.outputs.dest }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build azure function
        working-directory: apps/image-optimizer-azure
        run: pnpm build

      - name: Delete pnpm symlink
        working-directory: apps/image-optimizer-azure/azure
        run: rm -rf node_modules

      - name: npm install
        working-directory: apps/image-optimizer-azure/azure
        run: npm install

      - name: sanity check
        working-directory: apps/image-optimizer-azure/azure
        run: |
          ls
          cd src/functions && ls

      - name: deploy to azure function
        uses: Azure/functions-action@v1.5.1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
